### ISSUE TITLE
I encountered some problems during the test period which caused the test to fail

### ISSUE THREAD

**Issue by mdswyz** [mahmoudnafifi/image_relighting#1]
First of all, thank you very much for being able to open source this project, this project is great! I followed the steps in the readme to train all three models step by step, but during the testing phase, I followed your steps and an error occurred, and I could not compile the new executable file with the code you provided.
![1612626087(1)](https://user-images.githubusercontent.com/50685067/107122954-d3764b80-68d5-11eb-8c11-85902bcb41c9.jpg)

**Comment by mahmoudnafifi** [comment]
You need to install Matlab Runtime (in your case you need version 9.7). You can download it from [here](https://www.mathworks.com/products/compiler/matlab-runtime.html).

**Comment by mdswyz** [comment]
Thank you very much for your reply, I have passed the test.
