### ISSUE TITLE
About the 'gt_images_aug' and the 'target_aug'. Are they same?

### ISSUE THREAD

**Issue by wzy0903** [mahmoudnafifi/image_relighting#2]
About the 'gt_images_aug' and the 'target_aug'
Are they same? They are all generated by  demo_WB_color_augmentation.m, if I understand correctly.

Run the WB augmenter (with its default 2 augmented version in the given code) with the given demo_WB_color_augmentation.m file. Then, run demo_WB_color_augmentation.m. Change the directory to make input directory variable = 'input'. The code will generate for you augmented sets (name the result directory as 'input_aug' and the new gt directory as 'gt_images_aug'). Use those directories to train the normalization net.

Data Augmentation for Track 1 & 2:
Augment input images with WB augmenter to generate 10 augmented images for each original image. We assume the input images (after augmentation) are located in train_t1. For train_t1, the augmented data and new ground truth should be located in train_t1/input_aug and train_t1/target_aug. We have used the modified demo_WB_color_augmentation.m (given) to process input and target images for track 1.

**Comment by mahmoudnafifi** [comment]
Thanks for your question. 

Sorry for the confusion. No, `gt_images_aug` and `target_aug` are not the same.

* `gt_images_aug` is the ground-truth directory to train the normalization net. This is not the target of any of relighting tasks. 
* `target_aug` contains ground-truth data (of either task 1 or 2) after using the `WB augmenter` to augment the data. 

I hope this helps.

**Comment by wzy0903** [comment]
Thanks for your reply.
I am sorry for the trouble.
You mean use theWB correction and WB augmenter to processing the track 2 dataset, and to train the normalization net. 
Then use the WB augmenter to processing the track 1 dataset, and to train the relighting net?
Do I understand it right?

**Comment by mahmoudnafifi** [comment]
Right. The first part is to train the norm net. Then, the WB augmentation is optional to improve the results on tracks 1 & 2.

**Comment by wzy0903** [comment]
Thank you very much. This is very helpful to me.

**Comment by mahmoudnafifi** [comment]
my pleasure
