### ISSUE TITLE
Testing about the post_processing.exe

### ISSUE THREAD

**Issue by wzy0903** [mahmoudnafifi/image_relighting#3]
Thanks for your open source code. I am sorry for this trouble.
I had finished the training of the network.
Then I run the test.py to test the track1 problem. I got this problem:

INFO: Loading model ./models/relighting_net_one_to_one.pth
INFO: Loading model ./models/relighting_net_one_to_any.pth
INfo: Processing image ./track1_test/Image345.png ...
sh: 1 : post_processing.exe: not found
Post processing ...

This fiel does exist, and the program seems to have been suspended here.
Is it because my system is Linux and I can not run this file. But my windows machine doesn't have GPU. Does that mean I can't run this program?

Looking for your reply.

**Comment by mahmoudnafifi** [comment]
Hi, 

You can rebuild the post_processing.m (+ associated files in [bgu-master](https://github.com/mahmoudnafifi/image_relighting/tree/master/relighting/bgu-master)) in a Linux version of Matlab. This will need to change the code in test.py a bit to call the proper file after rebuilding. Another solution is to process the images in the downsized version and then do the post-processing later in Matlab using post_processing.m.

I hope this helps.
